import { gql } from "@apollo/client";
import client from "client";
import Head from "next/head";




export default async function Home() {
  const { data } = await client.query({
    query: gql`
      query GetPages {
        nodeByUri(uri: "/") {
          ... on Page {
            id
            content
            blocks
          }
        }
      }
    `,
  });



  return (
    <div>
      <Head>
        <title>Pages</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div dangerouslySetInnerHTML={{ __html: data?.nodeByUri.content }} />
  
    </div>
  );
}
